<a href="https://colab.research.google.com/github/saravananmaran/ALDS/blob/main/Day03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##EX 3.1


In [ ]:
import spacy
!python -m spacy download en_core_web_md
nlp = spacy.load("en_core_web_md")


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 44.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
doc = nlp(u"The quick brown fox jumped over the lazy dog.")
doc.vector

array([-6.97969019e-01,  5.56670018e-02, -1.62355408e-01,  2.68360879e-02,
       -9.58139636e-03, -2.15498973e-02, -2.48151012e-02, -1.04111791e-01,
        1.09173097e-01,  1.64876401e+00, -8.64830017e-02, -9.60250050e-02,
       -6.10291585e-02, -1.34389028e-02, -1.50561988e-01,  9.28654969e-02,
       -1.34864897e-01,  8.72585893e-01, -1.22531809e-01, -1.88338920e-01,
       -6.95055947e-02,  6.75773025e-02,  7.23951012e-02, -2.42390200e-01,
       -3.19726020e-02, -1.53924689e-01, -1.00833908e-01, -3.65620442e-02,
       -9.96995121e-02, -2.87402004e-01, -2.31279328e-01,  1.94752514e-01,
        1.13083087e-01, -8.84450302e-02,  1.84483200e-01,  1.19909093e-01,
       -1.52591199e-01,  1.30020012e-03, -2.64751583e-01,  3.17928940e-02,
        1.35594696e-01,  2.74599949e-03, -8.38430375e-02,  2.13983003e-02,
        1.69815883e-01, -3.98678072e-02, -9.36224982e-02, -1.14555992e-01,
        5.26507981e-02, -6.80560023e-02, -2.47021005e-01,  1.88996404e-01,
       -1.35233002e-02, -

In [ ]:
tokens = nlp(u"loin cat pet")
tokens

loin cat pet

In [ ]:
for token1 in tokens:
  for token2 in tokens:
    print(token1.text, token2.text, token1.similarity(token2))

loin loin 1.0
loin cat 0.24541720747947693
loin pet 0.24541720747947693
cat loin 0.24541720747947693
cat cat 1.0
cat pet 1.0000001192092896
pet loin 0.24541720747947693
pet cat 1.0000001192092896
pet pet 1.0


In [ ]:
nlp(u'lion').similarity(nlp(u'dandelion'))

0.344340443611145

In [ ]:
tokens = nlp(u'like love hate')
tokens

like love hate

In [ ]:
for token1 in tokens:
  for token2 in tokens:
    print(token1.text, token2.text, token1.similarity(token2))

like like 1.0
like love 1.0
like hate 1.0
love like 1.0
love love 1.0
love hate 1.0
hate like 1.0
hate love 1.0
hate hate 1.0


In [ ]:
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...


In [ ]:
a = 'This is a good movie'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.508, 'pos': 0.492, 'compound': 0.4404}

In [ ]:
a = 'This was the best, most awesome movie EVER MADE!!!'
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.425, 'pos': 0.575, 'compound': 0.8877}

In [ ]:
a = 'This was the worst film to ever disgrace the screen.'
sid.polarity_scores(a)

{'neg': 0.477, 'neu': 0.523, 'pos': 0.0, 'compound': -0.8074}

In [ ]:
a ='like good good very good nice amazing  best 100% love caring cute sexy lovable smartest positive super excellent '
sid.polarity_scores(a)

{'neg': 0.0, 'neu': 0.035, 'pos': 0.965, 'compound': 0.9952}

In [ ]:
import numpy as np
import pandas as pd
df = pd.read_csv('/amazonreviews.tsv', sep='\t')
df.head()

label                                             review
0   pos  Stuning even for the non-gamer: This sound tra...
1   pos  The best soundtrack ever to anything.: I'm rea...
2   pos  Amazing!: This soundtrack is my favorite music...
3   pos  Excellent Soundtrack: I truly like this soundt...
4   pos  Remember, Pull Your Jaw Off The Floor After He...

In [ ]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [ ]:
df.dropna(inplace=True)

In [ ]:
df['label'].value_counts()

label
neg    5097
pos    4903
Name: count, dtype: int64

In [ ]:
blanks = []
for i,lb,rv in df.itertuples():
  if type(rv)==str:
    if rv.isspace():
      blanks.append(i)

df.drop(blanks, inplace= True)
df['label'].value_counts()


label
neg    5097
pos    4903
Name: count, dtype: int64

In [ ]:
sid.polarity_scores(df.iloc[0]['review'])
df.loc[0]['label']

'pos'

In [ ]:
df['scores'] = df['review'].apply(lambda review: sid.polarity_scores(review))
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...

In [ ]:
sid.polarity_scores(df.loc[0]['review'])
df.loc[0]['scores']

{'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'compound': 0.9454}

In [ ]:
df['comp_score'] = df['scores'].apply(lambda d:d['compound'])
df.head()

label                                             review  \
0   pos  Stuning even for the non-gamer: This sound tra...   
1   pos  The best soundtrack ever to anything.: I'm rea...   
2   pos  Amazing!: This soundtrack is my favorite music...   
3   pos  Excellent Soundtrack: I truly like this soundt...   
4   pos  Remember, Pull Your Jaw Off The Floor After He...   

                                              scores  comp_score  
0  {'neg': 0.088, 'neu': 0.669, 'pos': 0.243, 'co...      0.9454  
1  {'neg': 0.018, 'neu': 0.837, 'pos': 0.145, 'co...      0.8957  
2  {'neg': 0.04, 'neu': 0.692, 'pos': 0.268, 'com...      0.9858  
3  {'neg': 0.09, 'neu': 0.615, 'pos': 0.295, 'com...      0.9814  
4  {'neg': 0.0, 'neu': 0.746, 'pos': 0.254, 'comp...      0.9781

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

df['pred_label'] = df['comp_score'].apply(lambda score: 'pos' if score >=0 else 'neg')

print(accuracy_score(df['label'],df['pred_label']))
print(classification_report(df['label'],df['pred_label']))
print(confusion_matrix(df['label'],df['pred_label']))

0.7098
              precision    recall  f1-score   support

         neg       0.86      0.52      0.64      5097
         pos       0.64      0.91      0.75      4903

    accuracy                           0.71     10000
   macro avg       0.75      0.71      0.70     10000
weighted avg       0.75      0.71      0.70     10000

[[2630 2467]
 [ 435 4468]]


## EX 3.2   (Keras Basics)

In [2]:
import numpy as np
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()
type(iris)

sklearn.utils._bunch.Bunch

In [4]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [5]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Cr

In [6]:
x = iris.data

In [7]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
y = iris.target

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
from tensorflow.keras.utils import to_categorical


In [13]:
y = to_categorical(y)

In [14]:
y.shape

(150, 3)

In [15]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [17]:
x_train

array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.7, 3

In [18]:
x_test

array([[6.1, 2.8, 4.7, 1.2],
       [5.7, 3.8, 1.7, 0.3],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 2.8, 4.8, 1.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [5.8, 2.7, 3.9, 1.2],
       [6.5, 3.2, 5.1, 2. ],
       [4.8, 3. , 1.4, 0.1],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.1, 3.8, 1.5, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.5, 3. , 5.8, 2.2],
       [5.6, 2.5, 3.9, 1.1],
       [5.7, 2.8, 4.5, 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5. , 3.4, 1.6, 0.4],
       [6.4, 2.8, 5.6, 2.1],
       [7.9, 3.8, 6.4, 2. ],
       [6.7, 3. , 5.2, 2.3],
       [6.7, 2.5, 5.8, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3. , 1.4, 0.3],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [4.4, 3

In [19]:
y_train

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0

In [20]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [21]:
from sklearn.preprocessing import MinMaxScaler

In [22]:
scalar_object = MinMaxScaler()

In [23]:
scalar_object.fit(x_train)

MinMaxScaler()

In [24]:
scalar_x_train = scalar_object.transform(x_train)

In [25]:
scalar_x_test = scalar_object.transform(x_test)

In [26]:
x_train.max()

np.float64(7.7)

In [28]:
scalar_x_train.min()

np.float64(0.0)

In [29]:
x_train

array([[5.7, 2.9, 4.2, 1.3],
       [7.6, 3. , 6.6, 2.1],
       [5.6, 3. , 4.5, 1.5],
       [5.1, 3.5, 1.4, 0.2],
       [7.7, 2.8, 6.7, 2. ],
       [5.8, 2.7, 4.1, 1. ],
       [5.2, 3.4, 1.4, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [5.1, 3.8, 1.9, 0.4],
       [5. , 2. , 3.5, 1. ],
       [6.3, 2.7, 4.9, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 2.7, 4.2, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [5.7, 3. , 4.2, 1.2],
       [7.7, 3.8, 6.7, 2.2],
       [4.6, 3.2, 1.4, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.7, 2.5, 5. , 2. ],
       [5.5, 4.2, 1.4, 0.2],
       [6. , 3. , 4.8, 1.8],
       [5.8, 2.7, 5.1, 1.9],
       [6. , 2.2, 4. , 1. ],
       [5.4, 3. , 4.5, 1.5],
       [6.2, 3.4, 5.4, 2.3],
       [5.5, 2.3, 4. , 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 2.7, 5.3, 1.9],
       [5. , 3.3, 1.4, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 2.4, 3.8, 1.1],
       [6.7, 3

##BUILDING THE NETWORK WITH KERAS


In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [31]:
import tensorflow as tf

In [33]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [34]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 139 (556.00 B)

 Trainable params: 139 (556.00 B)

 Non-trainable params: 0 (0.00 B)

###FIT (Train) the Model

In [35]:
model.fit(scalar_x_train, y_train, epochs=150, verbose=2)

Epoch 1/150
4/4 - 2s - 388ms/step - accuracy: 0.6200 - loss: 1.0501
Epoch 2/150
4/4 - 0s - 14ms/step - accuracy: 0.6200 - loss: 1.0415
Epoch 3/150
4/4 - 0s - 14ms/step - accuracy: 0.6400 - loss: 1.0338
Epoch 4/150
4/4 - 0s - 13ms/step - accuracy: 0.6500 - loss: 1.0265
Epoch 5/150
4/4 - 0s - 13ms/step - accuracy: 0.6500 - loss: 1.0195
Epoch 6/150
4/4 - 0s - 13ms/step - accuracy: 0.6500 - loss: 1.0124
Epoch 7/150
4/4 - 0s - 13ms/step - accuracy: 0.6500 - loss: 1.0054
Epoch 8/150
4/4 - 0s - 13ms/step - accuracy: 0.6500 - loss: 0.9987
Epoch 9/150
4/4 - 0s - 13ms/step - accuracy: 0.6500 - loss: 0.9919
Epoch 10/150
4/4 - 0s - 13ms/step - accuracy: 0.6500 - loss: 0.9851
Epoch 11/150
4/4 - 0s - 13ms/step - accuracy: 0.6500 - loss: 0.9774
Epoch 12/150
4/4 - 0s - 14ms/step - accuracy: 0.6500 - loss: 0.9701
Epoch 13/150
4/4 - 0s - 16ms/step - accuracy: 0.6500 - loss: 0.9619
Epoch 14/150
4/4 - 0s - 13ms/step - accuracy: 0.6500 - loss: 0.9540
Epoch 15/150
4/4 - 0s - 12ms/step - accuracy: 0.6500 - l

###

In [36]:
model.predict(scalar_x_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step


array([[1.9407487e-02, 6.3825816e-01, 3.4233430e-01],
       [9.8136586e-01, 1.8494211e-02, 1.3994600e-04],
       [2.3045712e-04, 1.2345459e-01, 8.7631482e-01],
       [1.6825227e-02, 6.0807478e-01, 3.7510002e-01],
       [6.8386481e-03, 4.5627677e-01, 5.3688455e-01],
       [9.6284109e-01, 3.6653340e-02, 5.0547387e-04],
       [5.8256838e-02, 7.6639873e-01, 1.7534439e-01],
       [1.2121262e-03, 2.2327377e-01, 7.7551413e-01],
       [4.9727997e-03, 2.9075950e-01, 7.0426768e-01],
       [3.6660701e-02, 6.9716668e-01, 2.6617271e-01],
       [4.4266852e-03, 4.2622888e-01, 5.6934434e-01],
       [9.7280025e-01, 2.6777022e-02, 4.2268119e-04],
       [9.8323464e-01, 1.6606150e-02, 1.5917003e-04],
       [9.7454262e-01, 2.5103265e-02, 3.5415273e-04],
       [9.8873681e-01, 1.1194702e-02, 6.8446258e-05],
       [1.7106770e-02, 7.0227069e-01, 2.8062260e-01],
       [1.0388508e-03, 2.0159797e-01, 7.9736316e-01],
       [3.8529314e-02, 6.6560817e-01, 2.9586247e-01],
       [2.5875786e-02, 6.670

In [37]:
model.metrics_names

['loss', 'compile_metrics']

In [38]:
model.evaluate(scalar_x_test, y_test)


2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9525 - loss: 0.2625 


[0.26085972785949707, 0.9599999785423279]

In [39]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [46]:
predicted_probabilities = model.predict(scalar_x_test)
predictions = np.argmax(predicted_probabilities, axis=1)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step


In [47]:
y_test.argmax(axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2])

In [48]:
confusion_matrix(y_test.argmax(axis=1), predictions)

array([[19,  0,  0],
       [ 0, 13,  2],
       [ 0,  0, 16]])

In [51]:
print(classification_report(y_test.argmax(axis=1), predictions))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.87      0.93        15
           2       0.89      1.00      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



###SAVE AND LOADING THE MODELS

In [59]:
model.save('myfirstmodel.keras')

In [60]:
from keras.models import load_model
newmodel = load_model('myfirstmodel.keras')

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 8 variables whereas the saved optimizer has 14 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [55]:
newmodel.predict(x_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step


array([[1.17905896e-15, 8.20324422e-05, 9.99917924e-01],
       [3.00597236e-03, 9.71310139e-01, 2.56839115e-02],
       [3.32849703e-21, 2.11345491e-06, 9.99997795e-01],
       [1.57841403e-15, 8.80050866e-05, 9.99911964e-01],
       [9.47505084e-17, 3.97724762e-05, 9.99960124e-01],
       [1.52976869e-03, 9.34125245e-01, 6.43449500e-02],
       [3.97973050e-13, 6.18916005e-04, 9.99381125e-01],
       [3.81944485e-18, 1.55519338e-05, 9.99984443e-01],
       [9.44597590e-16, 7.70404658e-05, 9.99922931e-01],
       [4.48573707e-14, 2.34385763e-04, 9.99765635e-01],
       [1.98214924e-17, 2.50364246e-05, 9.99974906e-01],
       [1.28308227e-02, 9.51420307e-01, 3.57488245e-02],
       [2.38021091e-02, 9.56943691e-01, 1.92542113e-02],
       [8.94792937e-03, 9.55845416e-01, 3.52065861e-02],
       [4.48164269e-02, 9.49219644e-01, 5.96402958e-03],
       [3.05472533e-16, 5.46821211e-05, 9.99945223e-01],
       [1.33940176e-18, 1.17076761e-05, 9.99988258e-01],
       [7.87821278e-14, 2.70526

In [61]:
newmodel.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 280 (1.10 KB)

 Trainable params: 139 (556.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 141 (568.00 B)